In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import KNNImputer

In [2]:
df1_2 = pd.read_csv('df1_2.csv', header=0)
df2_2 = pd.read_csv('df2_2.csv', header=0)

Para la normalización del presente conjunto de datos, se utilizará el algoritmo Min-Max Scaling.

In [3]:
df1_2.shape

(60000, 163)

In [4]:
df2_2.shape

(16000, 163)

In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# Suponiendo que tienes df1_2 y df2_2 ya cargados

# Combina los conjuntos de datos df1_2 y df2_2
combined_data = np.vstack((df1_2, df2_2))

# Crea una instancia del escalador MinMaxScaler
scaler = MinMaxScaler()

# Ajusta y transforma el conjunto de datos combinado
combined_data_normalized = scaler.fit_transform(combined_data)

# Ahora, separa los datos normalizados nuevamente en df1_3 y df2_3 y crea DataFrames
df1_3 = pd.DataFrame(combined_data_normalized[:len(df1_2)], columns=df1_2.columns)
df2_3 = pd.DataFrame(combined_data_normalized[len(df1_2):], columns=df2_2.columns)

# Verifica las dimensiones de los DataFrames normalizados si es necesario
print("df1_3 shape:", df1_3.shape)
print("df2_3 shape:", df2_3.shape)

df1_3 shape: (60000, 163)
df2_3 shape: (16000, 163)

In [6]:
df1_3.describe()

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
count,60000.000000,60000.000000,6.000000e+04,6.000000e+04,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,...,60000.000000,60000.000000,60000.000000,60000.000000,60000.000000,6.000000e+04,60000.000000,60000.000000,60000.000000,60000.000000
mean,0.016667,0.001382,1.762701e-01,1.671845e-05,0.000334,0.000573,0.000065,0.000093,0.000447,0.001209,...,0.005702,0.005574,0.004573,0.006834,0.007884,2.889233e-03,0.007160,0.001824,0.000193,0.000128
std,0.128020,0.003386,3.674866e-01,4.082483e-03,0.007543,0.010340,0.006031,0.003255,0.007811,0.010374,...,0.014771,0.014331,0.011976,0.019431,0.025256,1.439222e-02,0.023219,0.010334,0.008928,0.005088
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000019,8.447901e-09,4.892654e-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000037,0.000030,0.000027,0.000061,0.000012,9.198854e-07,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000717,8.541767e-08,2.679311e-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.002985,0.002946,0.002265,0.003288,0.002168,3.406336e-04,0.000196,0.000000,0.000000,0.000000
75%,0.000000,0.001133,7.143170e-07,4.855377e-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.005622,0.005776,0.004800,0.007008,0.006524,1.403013e-03,0.007201,0.000441,0.000000,0.000000
max,1.000000,0.063948,1.000000e+00,1.000000e+00,1.000000,1.000000,1.000000,0.392396,0.551087,0.867838,...,1.000000,1.000000,1.000000,1.000000,0.749721,1.000000e+00,1.000000,0.833642,1.000000,0.666279

In [7]:
df2_3.describe()

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
count,16000.000000,16000.000000,1.600000e+04,1.600000e+04,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,...,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000,16000.000000
mean,0.023438,0.001583,1.629502e-01,6.060243e-08,0.000367,0.000605,0.000035,0.000195,0.000715,0.001536,...,0.005963,0.005853,0.004824,0.007410,0.008452,0.002967,0.007450,0.001859,0.000137,0.000141
std,0.151293,0.011724,3.658422e-01,1.914879e-07,0.005962,0.008769,0.001900,0.008473,0.012244,0.013964,...,0.016059,0.015387,0.013002,0.021849,0.028363,0.013614,0.027710,0.011596,0.006836,0.008139
min,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000022,8.447901e-09,3.634543e-09,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000040,0.000033,0.000029,0.000066,0.000014,0.000001,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000721,8.354035e-08,1.821931e-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.003085,0.003028,0.002358,0.003386,0.002278,0.000351,0.000205,0.000000,0.000000,0.000000
75%,0.000000,0.001152,5.547455e-07,5.327168e-08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.005641,0.005809,0.004859,0.007037,0.006622,0.001423,0.007183,0.000421,0.000000,0.000000
max,1.000000,1.000000,9.999999e-01,1.013921e-05,0.524656,0.706826,0.218003,1.000000,1.000000,1.000000,...,0.690628,0.584763,0.500219,0.975768,1.000000,0.396984,0.891960,1.000000,0.705394,1.000000

In [10]:
df1_3.head(10)

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,0.0,1.785765e-03,9.999998e-01,3.261769e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.015918,0.013067,7.421784e-03,8.179508e-03,8.044604e-03,0.001321,0.003800,0.000000e+00,0.000000,0.000000
1,0.0,7.696916e-04,0.000000e+00,3.643862e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.005407,0.004716,3.019031e-03,4.272917e-03,3.170203e-03,0.000679,0.005064,3.281990e-04,0.000000,0.000000
2,0.0,9.555370e-04,1.070067e-07,1.164918e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.003559,0.004232,4.364196e-03,7.130884e-03,7.607928e-03,0.001321,0.004937,1.124629e-04,0.000000,0.000000
3,0.0,2.793968e-07,3.285295e-08,7.688457e-09,0.0,0.000498,0.0,0.0,0.0,0.000004,...,0.000003,0.000001,5.970003e-07,7.660803e-07,2.371948e-07,0.000000,0.000000,0.000000e+00,0.008299,0.018605
4,0.0,1.417333e-03,6.420405e-07,5.335323e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.007981,0.006086,4.171776e-03,6.044861e-03,6.806399e-03,0.002605,0.022523,2.664976e-04,0.000000,0.000000
5,0.0,8.920208e-04,9.999998e-01,2.539520e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.004986,0.007635,9.268224e-03,5.230448e-03,3.638568e-05,0.000003,0.000044,0.000000e+00,0.000000,0.000000
6,0.0,3.259629e-07,2.815967e-09,2.572138e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.000002,0.000001,6.175865e-07,4.875056e-07,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000,0.000000
7,0.0,2.397224e-03,9.999998e-01,1.351304e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.009181,0.010195,9.428261e-03,1.831917e-02,2.629712e-02,0.002856,0.006721,1.713636e-03,0.000000,0.000000
8,0.0,1.832284e-03,0.000000e+00,4.510561e-08,0.0,0.000000,0.0,0.0,0.0,0.000000,...,0.008973,0.009601,1.224909e-02,1.763210e-02,3.797251e-03,0.000529,0.002138,8.751973e-07,0.000000,0.000000
9,1.0,3.567059e-03,8.541767e-08,3.494753e-08,0.0,0.000000,0.0,0.0,0.0,0.000162,...,0.001666,0.000712,3.504186e-04,3.912581e-04,8.150487e-04,0.000000,0.000000,0.000000e+00,0.000000,0.000000

In [11]:
df2_3.head(10)

,class,aa_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,ag_003,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,0.0,0.000001,9.386557e-09,1.397901e-09,0.0,0.0,0.0,0.0,0.0,0.000037,...,0.000014,0.000004,0.000004,0.000011,0.000002,7.359084e-07,0.000000,0.000000,0.0,0.0
1,0.0,0.000002,3.191429e-08,4.659671e-09,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.000014,0.000007,0.000017,0.000002,0.000002,3.863519e-06,0.000000,0.000000,0.0,0.0
2,0.0,0.001537,9.949750e-08,1.304708e-08,0.0,0.0,0.0,0.0,0.0,0.002731,...,0.006353,0.010074,0.004530,0.004693,0.031192,1.285164e-03,0.000027,0.000000,0.0,0.0
3,0.0,0.001393,4.740211e-07,1.090363e-07,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.006939,0.006443,0.004975,0.008450,0.010232,1.756764e-03,0.014619,0.000707,0.0,0.0
4,0.0,0.000042,7.321514e-08,1.630885e-08,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.000098,0.000110,0.000190,0.000867,0.000075,4.030771e-06,0.000004,0.000000,0.0,0.0
5,0.0,0.000004,1.220252e-08,2.795802e-09,0.0,0.0,0.0,0.0,0.0,0.000005,...,0.000014,0.000008,0.000006,0.000005,0.000005,1.030606e-05,0.000000,0.000000,0.0,0.0
6,0.0,0.000936,3.003698e-07,7.059401e-08,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.006752,0.006349,0.004524,0.006516,0.004011,4.487201e-04,0.002131,0.000070,0.0,0.0
7,0.0,0.002800,9.999998e-01,2.982189e-08,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.012918,0.012174,0.009020,0.012005,0.013485,4.186516e-03,0.052245,0.007619,0.0,0.0
8,0.0,0.000340,9.999998e-01,1.887167e-08,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.001348,0.001520,0.000506,0.000666,0.005770,1.213780e-03,0.000000,0.000000,0.0,0.0
9,0.0,0.000660,9.999998e-01,2.772504e-08,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.004581,0.003974,0.002725,0.004166,0.003334,6.251040e-04,0.001711,0.000018,0.0,0.0

In [13]:
# Exportar df1_3 a un archivo CSV
df1_3.to_csv('df1_3.csv', index=False)

# Exportar df2_3 a un archivo CSV
df2_3.to_csv('df2_3.csv', index=False)

In [14]:
header1 = df1_3.head(10)
selected_columns = df1_3.columns[:5].tolist() + df1_3.columns[-5:].tolist()
header1 = header1[selected_columns]

# Guardar el encabezado como un archivo XLSX
header1.to_excel('normalized_values_TRS.xlsx', index=False)

In [15]:
header2 = df2_3.head(10)
selected_columns = df2_3.columns[:5].tolist() + df2_3.columns[-5:].tolist()
header2 = header2[selected_columns]

# Guardar el encabezado como un archivo XLSX
header2.to_excel('normalized_values_TES.xlsx', index=False)